### PR TITLE
Legacy browser support

### PR DESCRIPTION
**Pull request by donavon**

### CODE REVIEW

**Comment by coopersemantics** [comment]
:+1: :lipstick: :white_check_mark: - All is well

**Comment by pbouzakis** [comment]
:+1:

**Comment by erinzobitz** [comment]
:shipit:

**Comment by jfkhoury** [comment]
:sleepy:  :sleepy:  :sleeping:

**Comment by bionicbrian** [comment]
:mans_shoe:

**Comment by donavon** [comment]
For the record: Paul prematurely closed this pull request.

**Pull request closed without merging**
